### ISSUE TITLE
Update class to conform to September 2022 new formatting guide

### ISSUE THREAD

**Issue by amunn** [amunn/msu-thesis#20]
In September 2022, the Grad School changed the formatting requirements in various places, and as of now the class produces non-conforming documents. This issue is a placeholder for revisions to the class to make it conforming again.

**Comment by clairekope** [comment]
Disclaimer, I haven't yet sent my dissertation off to ProQuest :)
But these are the patches I made for the purposes of submission.

Easy fixes for the two biggest changes: 
- Comment out or delete `\listoftables` and `\listoffigures` to remove the List of Tables and Figures respectively.
- Add `\settocdepth{chapter}` or `\settocdepth{section}` above `\tableofcontents*` for recommended or extended Table of Contents, respectively.

Below are fixes to some other issues that require editing the `.cls` file itself. How much do they care about these? No idea. Dual Major is probably the most important (and personally relevant for me).
- Dual Majors have to take up two lines on the title page for their field of study. Edit the following:
    * To line 283, below `\newcommand*{fieldofstudy}`, add: `\newcommand*{\dualmajor}[1]{\gdef\msu@dualmajor{#1}}`
    * To line 305 (306 after the above insertion), before the final `[\onelineskip]}` add `\msu@dualmajor~\msu@fieldseparator~Dual Major\\`
    * In your document preamble, define `\dualmajor{field}` just as you would `\fieldofstudy{field}`
- It appears the copyright should now be left-aligned and centered on the page. Around line 613 (`\newcommand*{\makecopyrightpage}`):
    * Switch `\raggedleft` to `\raggedright`
    * Switch `\vspace*{7in}` to `\vspace*{4in}`
- For extra title page security, change degree separator to match the example PDF:
    * Line 286: `\newcommand*{\msu@fieldseparator}{\textendash}` to `\newcommand*{\msu@fieldseparator}{\textemdash}`
    * Line 306: replace all instances of `~\msu@fieldseparator~` to ` \msu@fieldseparator ` to remove the extra space surrounding the separator. Spaces around `\msu@fieldseparator` are required for LaTeX parsing but will not show in the final document.

I haven't adjusted vertical spacing for things on the title page. The sample document suggests they want lines to fall at certain inches from the top. I'll test their dedication to this.

**Comment by amunn** [comment]
Dear Claire, thanks so much for these suggestions. This semester has been super busy for me and I simply haven't had time to implement the changes yet so this helps a lot. BTW the development branch version of the class solves your hyperref problem, but again, I haven't had time to do more exhaustive testing to to make sure it's  bug free for the more complicated per-chapter type thesis styles, which is why I haven't released it yet.

**Comment by clairekope** [comment]
More changes for title page spacing; have not yet submitted.

I realized they probably are going to be sticklers for title page spacing since they're pushing MS Word templates.
The issue with putting this into LaTeX is that the sample PDF has lines pegged to particular inches from the top of the page, while as far as I can tell, LaTeX can only define blank space relative to the last line you've printed on (not top of page). So here are updates with a bunch of relative spacing between title page elements.

Disclaimer: still not yet submitted, but I checked against the example with a ruler. **Depending on the length of your title and whether or not you have a dual degree you will need to adjust some spacings.** Note that the example PDF doesn't precisely conform to the stated inch markings because Word just.... isn't that precise without a lot of fiddling. I conformed to the provided PDF example rather than the stated lengths.

All of the following changes occur around line 300:
- `\posttitle{\end{center}\vspace{0.96in}}` **if your title is more than one line you will need to shorten this**
- `\preauthor{\begin{center}By\\ \vspace{0.34in}}`
- `\predate{\vspace{2.4in}\begin{center}\msu@titleintro\msu@thesistype\\ \vspace{0.375in} Submitted to\\`... etc.
- **If you do not have a Dual Major** you will need to replace the final `[\onelineskip]` on the above line with some `\vspace{length}` but I haven't bothered to figure out what that length should be. The idea is that the year will be at the same height on the page regardless of whether or not your degree has the Dual Major on a second line or not.

**Comment by GioPede** [comment]
Hi! Does anyone know what to do with the inversion of the appendix and bibliography mandated by the new guidelines? (how would one cite something in the appendix if the bib is printed above it?)
Also, are the "part" cover pages of the appendix and bibliography still needed? It is all very unclear to me

**Comment by amunn** [comment]
Hi, @GioPede the inversion of the appendix and bibliography is a tour de force of stupidity which shows how little the people in the thesis office understand document structure. But from a practical point of view, any citations in your appendices will also show up in the bibliography even though it comes before, so just cite things as you normally would.  And no, the cover pages for these sections are no longer required. I'm sorry I haven't had time this semester to push out a revised version of the class. Please check out @clairekope 's helpful suggestions in this thread. I will try to get a new version out by the end of the semester.

**Comment by GioPede** [comment]
I know the actual citation will work, I'm just puzzled by them coming before the text, but yes, it seems the changes were completely arbitrary and stupid. 
I will probably end up removing the appendix and appendices environments entirely and manually adding the entries to the TOC (unfortunately i have per-chapter appendices and bibs... the worst case scenario!) If i make any modifications that are general enough, I'll make some pull requests

**Comment by amunn** [comment]
@GioPede Unfortunately the coverpages are built into the `appendi{x|ces}` environments, so there's no simple fix for them at the moment.

**Comment by clairekope** [comment]
@GioPede you could rearrange the document in post. The ToC will be wrong and you shouldn't use hyperref, but if you're already creating a hack job of a document, you could type up a ToC in Word, export to PDF, and splice it in. My favorite tool for command line PDF rearranging is pdftk if you'd like a suggestion. 

Edit to add, sounds like you've already got something like this in mind :)

**Comment by clairekope** [comment]
I return from the first attempt at submission with more nitpicks, mostly on spacing (incredibly, not on the title page). Thesis office seems to want spacing between chapter titles to match spacing between body text and now wants a very minimal abstract header.
- In the class file:
   * Having `\setlength{\afterchapskip}{0.5\onelineskip}` instead of `2\onelineskip` should do the trick for almost all chapter heads
   * Comment out or remove `\begin{center}
    	\MakeUppercase{\thetitle}\plainbreak{1}By\plainbreak{1}\theauthor
 	\end{center}` within `\renewenvironment{abstract}`
- In your main tex file
    * set `\setabstractnamespace{-0.5}` to adjust the abstract header to be in line with the other chapters
    * No longer need bibliography cover pages! Remove those calls to `\makebibliographypage`
    
Nitpicks you may also encounter depending on your circumstances:
- All links have to be in black. Adjust your hyperref package settings accordingly.
- URLs can't be in monospace, so add `\urlstyle{same}` into your main tex file
- They don't want ToC entries to be "unnecessarily hyphenated" so if you have long chapter or section titles, they want you to break them up with newlines. Follow this stack overflow entry: https://tex.stackexchange.com/questions/328613/insert-a-line-break-into-a-toc-item-without-breaking-the-line-in-the-chapter-tit

**Comment by clairekope** [comment]
More nitpicks and updates:
- The **spacing for all headers** has to be horrendous (double spaced, just like the rest of the text) so you'll have to add the following to the class file:
   * `\setlength{\aftersecskip}{0.5\onelineskip}`
   * `\setlength{\beforesubsecskip}{0pt}`
   * `\setlength{\aftersubsecskip}{0.5\onelineskip}`
   * `\setlength{\beforesubsubsecskip}{0pt}`
   * `\setlength{\aftersubsubsecskip}{0.5\onelineskip}`
- **Caveat to removing `\makebibliographypage` I mentioned above** is that this command also removes the bibliography from the table of contents.
    * if you're using biblatex, you can just adjust `\printbibliography` to `\printbibliography[heading=bibintoc]`
    * Otherwise, edit `\newcommand\msu@bibpage` to keep the ToC functionality but remove the page when calling `\makebibliographypage`

I also realized that you're using hyperref, you can make the PDF bookmarks go to a deeper level than the minimal ToC required by the grad school with the `bookmarksdepth` package option (you know, if you want a more navigable document!) I have `bookmarksdepth=4` to capture headers down to subsubsections.

**Comment by amunn** [comment]
@clairekope @GioPede  Just in time for the Dec 15 deadline I've managed to release an updated version of the class that conforms to the current requirements. Thanks for your comments and patience! Beware that the thesis office is being really annoying these days about line spacing to the point that they may be requesting things that are impossible.
